[package]
name = "sculpter"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
ab_glyph.workspace = true
etagere.workspace = true
fixed.workspace = true
harfrust.workspace = true
image.workspace = true
language-tags.workspace = true
log.workspace = true
read-fonts.workspace = true
skrifa.workspace = true
thiserror.workspace = true
