[package]
name = "scribble-reader-desktop"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
dotenv.workspace = true
env_logger.workspace = true
log.workspace = true
scribble-reader.workspace = true
scribe.workspace = true
winit.workspace = true
wrangler.workspace = true
xdg.workspace = true
